name: contact_book
description: STdev project


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^5.1.0
  
  provider: ^6.0.5
  get_it: ^7.6.0
  get: ^4.6.5
  dio: ^5.3.2
  shared_preferences: ^2.2.0
  flutter_spinkit: ^5.2.0
  animate_do: ^3.0.2
  iconsax: ^0.0.8
  shimmer: ^3.0.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 900
  assets:
   - assets/images/